/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as EstimateRouteRouteImport } from './routes/estimate/route'
import { Route as EstimatesRouteImport } from './routes/estimates'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as RateRouteImport } from './routes/rate'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as TimeRouteImport } from './routes/time'
import { Route as EstimateIndexRouteImport } from './routes/estimate/index'
import { Route as EstimateAutoRouteImport } from './routes/estimate/auto'
import { Route as EstimateCustomRouteImport } from './routes/estimate/custom'
import { Route as EstimateWebsiteRouteImport } from './routes/estimate/website'
import { Route as EstimatesIdRouteImport } from './routes/estimates.$id'
import { Route as InvoicesIdRouteImport } from './routes/invoices.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimateRouteRoute = EstimateRouteRouteImport.update({
  id: '/estimate',
  path: '/estimate',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimatesRoute = EstimatesRouteImport.update({
  id: '/estimates',
  path: '/estimates',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const RateRoute = RateRouteImport.update({
  id: '/rate',
  path: '/rate',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeRoute = TimeRouteImport.update({
  id: '/time',
  path: '/time',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimateIndexRoute = EstimateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EstimateRouteRoute,
} as any)
const EstimateAutoRoute = EstimateAutoRouteImport.update({
  id: '/auto',
  path: '/auto',
  getParentRoute: () => EstimateRouteRoute,
} as any)
const EstimateCustomRoute = EstimateCustomRouteImport.update({
  id: '/custom',
  path: '/custom',
  getParentRoute: () => EstimateRouteRoute,
} as any)
const EstimateWebsiteRoute = EstimateWebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => EstimateRouteRoute,
} as any)
const EstimatesIdRoute = EstimatesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EstimatesRoute,
} as any)
const InvoicesIdRoute = InvoicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => InvoicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/estimate': typeof EstimateRouteRouteWithChildren
  '/clients': typeof ClientsRoute
  '/estimates': typeof EstimatesRouteWithChildren
  '/invoices': typeof InvoicesRouteWithChildren
  '/rate': typeof RateRoute
  '/studio': typeof StudioRoute
  '/time': typeof TimeRoute
  '/estimate/auto': typeof EstimateAutoRoute
  '/estimate/custom': typeof EstimateCustomRoute
  '/estimate/website': typeof EstimateWebsiteRoute
  '/estimates/$id': typeof EstimatesIdRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/estimate/': typeof EstimateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clients': typeof ClientsRoute
  '/estimates': typeof EstimatesRouteWithChildren
  '/invoices': typeof InvoicesRouteWithChildren
  '/rate': typeof RateRoute
  '/studio': typeof StudioRoute
  '/time': typeof TimeRoute
  '/estimate/auto': typeof EstimateAutoRoute
  '/estimate/custom': typeof EstimateCustomRoute
  '/estimate/website': typeof EstimateWebsiteRoute
  '/estimates/$id': typeof EstimatesIdRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/estimate': typeof EstimateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/estimate': typeof EstimateRouteRouteWithChildren
  '/clients': typeof ClientsRoute
  '/estimates': typeof EstimatesRouteWithChildren
  '/invoices': typeof InvoicesRouteWithChildren
  '/rate': typeof RateRoute
  '/studio': typeof StudioRoute
  '/time': typeof TimeRoute
  '/estimate/auto': typeof EstimateAutoRoute
  '/estimate/custom': typeof EstimateCustomRoute
  '/estimate/website': typeof EstimateWebsiteRoute
  '/estimates/$id': typeof EstimatesIdRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/estimate/': typeof EstimateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/estimate'
    | '/clients'
    | '/estimates'
    | '/invoices'
    | '/rate'
    | '/studio'
    | '/time'
    | '/estimate/auto'
    | '/estimate/custom'
    | '/estimate/website'
    | '/estimates/$id'
    | '/invoices/$id'
    | '/estimate/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clients'
    | '/estimates'
    | '/invoices'
    | '/rate'
    | '/studio'
    | '/time'
    | '/estimate/auto'
    | '/estimate/custom'
    | '/estimate/website'
    | '/estimates/$id'
    | '/invoices/$id'
    | '/estimate'
  id:
    | '__root__'
    | '/'
    | '/estimate'
    | '/clients'
    | '/estimates'
    | '/invoices'
    | '/rate'
    | '/studio'
    | '/time'
    | '/estimate/auto'
    | '/estimate/custom'
    | '/estimate/website'
    | '/estimates/$id'
    | '/invoices/$id'
    | '/estimate/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EstimateRouteRoute: typeof EstimateRouteRouteWithChildren
  ClientsRoute: typeof ClientsRoute
  EstimatesRoute: typeof EstimatesRouteWithChildren
  InvoicesRoute: typeof InvoicesRouteWithChildren
  RateRoute: typeof RateRoute
  StudioRoute: typeof StudioRoute
  TimeRoute: typeof TimeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimate': {
      id: '/estimate'
      path: '/estimate'
      fullPath: '/estimate'
      preLoaderRoute: typeof EstimateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimates': {
      id: '/estimates'
      path: '/estimates'
      fullPath: '/estimates'
      preLoaderRoute: typeof EstimatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rate': {
      id: '/rate'
      path: '/rate'
      fullPath: '/rate'
      preLoaderRoute: typeof RateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time': {
      id: '/time'
      path: '/time'
      fullPath: '/time'
      preLoaderRoute: typeof TimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimate/': {
      id: '/estimate/'
      path: '/'
      fullPath: '/estimate/'
      preLoaderRoute: typeof EstimateIndexRouteImport
      parentRoute: typeof EstimateRouteRoute
    }
    '/estimate/auto': {
      id: '/estimate/auto'
      path: '/auto'
      fullPath: '/estimate/auto'
      preLoaderRoute: typeof EstimateAutoRouteImport
      parentRoute: typeof EstimateRouteRoute
    }
    '/estimate/custom': {
      id: '/estimate/custom'
      path: '/custom'
      fullPath: '/estimate/custom'
      preLoaderRoute: typeof EstimateCustomRouteImport
      parentRoute: typeof EstimateRouteRoute
    }
    '/estimate/website': {
      id: '/estimate/website'
      path: '/website'
      fullPath: '/estimate/website'
      preLoaderRoute: typeof EstimateWebsiteRouteImport
      parentRoute: typeof EstimateRouteRoute
    }
    '/estimates/$id': {
      id: '/estimates/$id'
      path: '/$id'
      fullPath: '/estimates/$id'
      preLoaderRoute: typeof EstimatesIdRouteImport
      parentRoute: typeof EstimatesRoute
    }
    '/invoices/$id': {
      id: '/invoices/$id'
      path: '/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof InvoicesIdRouteImport
      parentRoute: typeof InvoicesRoute
    }
  }
}

interface EstimateRouteRouteChildren {
  EstimateAutoRoute: typeof EstimateAutoRoute
  EstimateCustomRoute: typeof EstimateCustomRoute
  EstimateWebsiteRoute: typeof EstimateWebsiteRoute
  EstimateIndexRoute: typeof EstimateIndexRoute
}

const EstimateRouteRouteChildren: EstimateRouteRouteChildren = {
  EstimateAutoRoute: EstimateAutoRoute,
  EstimateCustomRoute: EstimateCustomRoute,
  EstimateWebsiteRoute: EstimateWebsiteRoute,
  EstimateIndexRoute: EstimateIndexRoute,
}

const EstimateRouteRouteWithChildren = EstimateRouteRoute._addFileChildren(
  EstimateRouteRouteChildren,
)

interface EstimatesRouteChildren {
  EstimatesIdRoute: typeof EstimatesIdRoute
}

const EstimatesRouteChildren: EstimatesRouteChildren = {
  EstimatesIdRoute: EstimatesIdRoute,
}

const EstimatesRouteWithChildren = EstimatesRoute._addFileChildren(
  EstimatesRouteChildren,
)

interface InvoicesRouteChildren {
  InvoicesIdRoute: typeof InvoicesIdRoute
}

const InvoicesRouteChildren: InvoicesRouteChildren = {
  InvoicesIdRoute: InvoicesIdRoute,
}

const InvoicesRouteWithChildren = InvoicesRoute._addFileChildren(
  InvoicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EstimateRouteRoute: EstimateRouteRouteWithChildren,
  ClientsRoute: ClientsRoute,
  EstimatesRoute: EstimatesRouteWithChildren,
  InvoicesRoute: InvoicesRouteWithChildren,
  RateRoute: RateRoute,
  StudioRoute: StudioRoute,
  TimeRoute: TimeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
